### ISSUE TITLE
[Suggestion] replacement keys

### ISSUE THREAD

**Issue by FaultyFunctions** [Konstanius/MineCICD#18]
I'm imagining something like a reverse secrets.yml. When you pull from the repo it will replace keys you have configured. The reason this is helpful is because if I have a dev server, sometimes I need to change the plugins MySQL config so it doesn't connect to my production server's databases, but I still want to track those config files.

Let me know if there is another way to accomplish this.

**Comment by Konstanius** [comment]
I don't think I fully understand exactly what you intend on doing here.
Can you please elaborate this further, also by giving an example of what the repository files contain and what your servers files contain?

**Comment by FaultyFunctions** [comment]
Okay for example I have a production server (on a host) and a development server (on my home computer). The config files for CoreProtect (for example) connect my production server's database. However, when I'm running my dev server I don't want CoreProtect to connect to my production database, and maybe I want it to connect to a dev database for testing. Currently I either have to completely disable CoreProtect to prevent that it from connecting to the production database, or manually change the database settings in the config.yml to my dev database and then discard those changes when I push to the prod server every time. I'm wanting a way to have MineCICD set the database info in config.yml to different information depending on if I'm working on my prod server or dev server.

So for a more concrete example. Here is the config for CoreProtect's Database on the production server and on the repo:
```yml
use-mysql: true
table-prefix: co_
mysql-host: '99.99.99.999.99'
mysql-port: 3306
mysql-database: prod_database_name
mysql-username: prod_username
mysql-password: prod_password
```
Now I want to pull from the repo onto my dev server to do some work. I want MineCICD to automatically set this config to:
```yml
use-mysql: true
table-prefix: co_
mysql-host: '22.22.222.22'
mysql-port: 3306
mysql-database: dev_database_name
mysql-username: dev_username
mysql-password: dev_password
```
Once I'm done doing work, I can use `secrets.yml` to change these values back to my production server values when I push to the repo.

So the only piece missing is changing the config values when I pull from the repo, rather than when I push to the repo (secrets.yml). So that's kind of why I called it a reverse secrets.yml.

Let me know if this makes sense, thanks!
