### ISSUE TITLE
secrets.yml configuration troubleshooting

### ISSUE THREAD

**Issue by Brickgard** [Konstanius/MineCICD#20]
I am attempting to use the secrets.yml to configure local-unique values in shared configurations.

For example, each server uses a unique voice chat port, but the rest of the config should be the same between servers - seems like a perfect opportunity to have it configured as:

`/plugins/voicechat/voicechat-server.properties`
```
port={{voice_port}}
codec=VOIP
```
and to have a secrets.yml that appears as
```yaml
voicechat:
  file: "plugins/voicechat/voicechat-server.properties"
  voice_port: 7005
```

However, as I've built towards this the results have been spotty - after setting this up from scratch several times, the workflow of:\
`dev staging` -> push to repo -> pull from repo to `new server` hoping for secret changes\
seems to do nothing, leaving the config as `port={{voice_port}}` often.

My confusion is because the `dev staging` source seems to push/pull this secret behavior fine (repo gets secret key, server sets its own value accordingly) while a new server pulling with the same secrets and keys fails to convert these values.

Other tests such as a Luckperms configuration seems to hit-and-miss, such as right now having a `new server` stuck with a Luckperms config as a local change (seemingly due to this secret) `/git resolve reset-local-changes` seems to do nothing.  I've reverted and re-pulled, force pulled, etc. and these behaviors consistently persist as long as a secret.yml change tries to affect this:
```yaml
luckperms:
  file: "plugins/LuckPerms/config.yml"
  perm_context: global
  perm_database: my_database
  perm_user: my_username
  perm_pass: 'my_pass'
  perm_redis: true
voicechat:
  file: "plugins/voicechat/voicechat-server.properties"
  voice_port: 7005
```
^ this on a fresh server results in LuckPerms/config.yml correctly converting its secret keys, being stuck as a local diff change regardless of reset-local-changes and such, and the voicechat keys never apply.  No errors and usual behavior otherwise.

Tested on latest Paper: `1.21.4-2412-9249a2c (MC: 1.21.4)`
Using latest MineCICD: 2.2.1
Pulling from branch `test`, _not_ `main` or `master`
Tested by making a fresh server, installing MineCICD configured to point to repo/branch, adding a secrets.yml and pulling.

Any guidance would be appreciated, as I'm hours in to what felt like should be quite simple, so I'm quite lost by this point.
